baseURL = "https://blog.wrhansen.dev/"
languageCode = "en-us"
title = "wrhansen.dev"
theme = "solar-theme-hugo"
author = "Wesley Hansen"
enableGitInfo = true
enableEmoji = true
paginate = 5
pygmentsStyle = "solarized-dark"

[params]
    contentTypeName = "posts"
    scheme = "preference" # light, dark, gray or preference
    description = "rantings and ravings"

[menu]
    [[menu.main]]
        name = "About"
        url = "/about"

[markup]
    [markup.highlight]
        style='solarized-dark'
        tabWidth = 4
